### ISSUE TITLE
Remove AC from closet window

### ISSUE THREAD

**Issue by thisisdano** [frangrit/schmooble-terrace#11]
It's winter, and an AC in the window is making that room cold cold cold.

### todo
- [x] remove AC from window
- [x] make sure window has a good seal
- [x] bring AC to crawl space

**Comment by thisisdano** [comment]
Stored in closet crawlspace. Seal is OK, but should be winterized like the other windows in the house.
